
name: nms_downloader
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  flutter_inappwebview: ^6.1.5
  provider: ^6.1.5+1
  google_fonts: ^6.3.1
  video_player: ^2.10.0
  flutter_downloader: ^1.12.0
  youtube_explode_dart: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
